name: test-workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo `date`
          echo "PY_VERSION=$(python --version)" >> "$GITHUB_ENV"
      - name: Printouts
        run: |
          echo "Python version: $PY_VERSION"
      - name: checkout
        uses: actions/checkout@v3
          
