name: test-workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: |
          echo `date`
          echo "PY_VERSION=$(python --version)" >> "$GITHUB_ENV"
          echo "Python version: ${PY_VERSION}"
      - name: checkout
        uses: actions/checkout@v3
          
