name: test-workflow
on: workflow_dispatch
jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "PY_VERSION=$(python --version)" >> "$GITHUB_ENV"
      - name: Printouts
        run: |
          echo `date`
          echo "Python version: $PY_VERSION"
          echo "Python version: $PY_VERSION" > py_version.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: py_version
          path: py_version.txt
  deploy:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: py_version
      - name: Get value from artifact
        shell: bash
        run: |
          version=`cat py_version.txt`
          echo "$version"
      - name: checkout
        uses: actions/checkout@v3
          
