name: test-workflow
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev*'
    paths-ignore:
      - '.github/workflows/*.yml'
jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      pyver: ${{ steps.setvars.outputs.PY_VERSION_OUTPUT  }}
    steps:
      - name: Set Variables
        id: setvars
        run: |
          echo "PY_VERSION=$(python --version)" >> "$GITHUB_ENV"
          echo "PY_VERSION_OUTPUT=$(python --version)" >> "$GITHUB_OUTPUT"
      - name: Printouts
        shell: bash
        run: |
          echo `date`
          echo "Github context: ${{ toJSON(github) }}"
          echo "Python version: $PY_VERSION" > py_version.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: py_version
          path: py_version.txt
  deploy:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: py_version
      - name: Get value from artifact
        shell: bash
        run: |
          version=`cat py_version.txt`
          echo "$version"
      - name: Get output
        run: |
          echo "${{ needs.set-vars.outputs.pyver }}"
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::319538390009:role/alexg-github-oidc
          role-session-name: GHactions
          aws-region: eu-west-1
      - name: Install Packages
        run: |
          pip install boto3
      - name: Run Python Script
        run: |
          output=$(python .github/workflows/get_buckets.py)
          echo "${output}"
      - name: Open file produced by python script
        run: |
          buckets=`cat buckets.txt`
          echo "$buckets"
