name: test-workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev*'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      pyver: ${{ steps.setvars.outputs.PY_VERSION_OUTPUT  }}
    steps:
      - name: Set Variables
        id: setvars
        run: |
          echo "PY_VERSION=$(python --version)" >> "$GITHUB_ENV"
          echo "PY_VERSION_OUTPUT=$(python --version)" >> "$GITHUB_OUTPUT"
      - name: Printouts
        shell: bash
        run: |
          echo `date`
          echo "Github context: ${{ toJSON(github) }}"
          echo "Python version: $PY_VERSION" > py_version.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: py_version
          path: py_version.txt
  deploy:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: py_version
      - name: Get value from artifact
        shell: bash
        run: |
          version=`cat py_version.txt`
          echo "$version"
      - name: Get output
        run: |
          echo "${{ needs.set-vars.outputs.pyver }}"
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-duration-seconds: 1200
          role-session-name: GHactions
      - name: Run Python Script
        run: |
          python .github/workflows/get_buckets.py
          
