name: test-workflow-ec2-selfhosted
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev*'
    paths-ignore:
      - '.github/workflows/*.yml'
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::319538390009:role/alexg-github-oidc
          role-session-name: GHactions
          aws-region: eu-north-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: maytan-cogo/ec2-github-runner@v2.0.0
        with:
          mode: start
          github-token: ${{ secrets.CODES_ACTIONS_PAT}}
          ec2-image-id: ami-0f5dba1a120f7b7ee
          ec2-instance-type: t3.micro
          subnet-id: subnet-01ac06a2836c4586b
          security-group-id: sg-08c0b211541df7791
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
  deploy:
    name: Do the job on the runner
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Checkout codes repo
        uses: actions/checkout@v3
        with:
          repository: alexgrud/gh-actions-codes
          token: ${{ secrets.CODES_ACTIONS_PAT }}
          path: codes
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::319538390009:role/alexg-github-oidc
          role-session-name: GHactions
          aws-region: eu-north-1
      - name: Install Packages
        run: |
          sudo yum install pip -y
          sudo pip install boto3
      - name: Run Python Script
        run: |
          output=$(python3 codes/get_buckets.py)
          echo "${output}"
      - name: Open file produced by python script
        run: |
          buckets=`cat buckets.txt`
          echo "$buckets"
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - deploy # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::319538390009:role/alexg-github-oidc
          role-session-name: GHactions
          aws-region: eu-north-1
      - name: Stop EC2 runner
        uses: maytan-cogo/ec2-github-runner@v2.0.0
        with:
          mode: stop
          github-token: ${{ secrets.CODES_ACTIONS_PAT }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
